#pragma once

// ---- build target ---------------------------------------------------------
// BUILD_DEBUG: profiling raster bar, KPrintF, WinUAE debug-overlay hooks,
//              warpmode() around precalc, the startup banner.
// Override from the Makefile with -DBUILD_DEBUG=0 for a release build.
#ifndef BUILD_DEBUG
#define BUILD_DEBUG 1
#endif

// CHEAT_MODE is generated by make; defaults off for standalone compilation.
#ifndef CHEAT_MODE
#define CHEAT_MODE 0
#endif

// PAL/NTSC is detected from the running raster at startup.
#include "video.h"

// Initial menu selection: 0=Hexagon, 1=Hexagoner, 2=Hexagonest.
// All six profiles are available in the runtime selector.
#ifndef PC_START_STAGE
#define PC_START_STAGE 0
#endif
#if PC_START_STAGE < 0 || PC_START_STAGE > 2
#error "PC_START_STAGE currently supports 0 (Hexagon), 1 (Hexagoner), or 2 (Hexagonest)"
#endif

// Initial menu bank: 0=normal, 1=hyper. Does not bypass session unlocks.
#ifndef PC_START_HYPER
#define PC_START_HYPER 0
#endif
#if PC_START_HYPER != 0 && PC_START_HYPER != 1
#error "PC_START_HYPER must be 0 or 1"
#endif

// Display cadence is independent of the 60 Hz reference simulation.
#define DISPLAY_RATE (video_timing.rate)
#define FRAME_RATE 60 // simulation ticks per second (legacy consumers)

// Startup banner text (BUILD_DEBUG only). Pick one.
#define DEBUG_NAG
//#define DEBUG_NGD
//#define DEBUG_SPAG

// ---- renderer tuning ----------------------------------------------------
#define ASM_OPT           // hand-tuned m68k asm in the hot clip/line paths
//#define SHOW_DRAW_PLANE  // show the work buffer as a 2nd bitplane
//#define SKIP_FILL        // skip the area fill (wireframe)

// Polygon morph buffers support up to six sides.
#define MAX_NUM_SIDES (6)

#define SCREEN_WIDTH (320) // Currently fixed at 320 due to cls routine
#define SCREEN_HEIGHT (200) // Must be multiple of 4 for cls routine
#define SCREEN_WIDTH_BYTES (SCREEN_WIDTH >> 3)

// Pixel geometry is handled by polar_to_cartesian(), identically in both modes.

#define BITPLANE_SIZE (SCREEN_HEIGHT * SCREEN_WIDTH_BYTES)

// Raw hardware coordinates (DIWSTRT space) of the visible display's top-left
// corner. screenScanDefault() uses these for DIWSTRT/DIWSTOP; the sprite HUD
// shares them so sprites line up with the bitplane display.
#define DISPLAY_HW_X (129 + (SCREEN_WIDTH - 320) / 2)
#define DISPLAY_VISIBLE_HEIGHT (video_timing.visible_height)
#define DISPLAY_HW_Y (44 + (DISPLAY_VISIBLE_HEIGHT - SCREEN_HEIGHT) / 2)

// Viewport clipping bounds and line-slope fixed point
#define XMAX (SCREEN_WIDTH-1)
#define YMAX (SCREEN_HEIGHT-1)
#define FRACBITS 8

#ifndef SOUND_EFFECTS
#define SOUND_EFFECTS 1
#endif
