#!/usr/bin/env python3
"""Derive native-only guards without editing the archival disassembly."""
from pathlib import Path
root = Path(__file__).resolve().parents[2]
source = (root / 'DiskIO.s').read_text()
for label in ('diskio_L06dc:', 'diskio_L01fc:', 'diskio_L023e:', 'diskio_L05ec:'):
    assert source.count(label) == 1
    source = source.replace(label, label + '\n        bsr.w native_disk_guard')
source += '''
; Enabled only within an established native save media sequence. Cold boot and
; the first identity read must still allow stepping to clear an insertion latch.
; Check the DMA polling loop before accepting completion; abort also stops DMA.
; Abort the entire driver call, including retry/recalibration paths. A6 is the
; driver's frame; discard nested helper return addresses before normal cleanup.
native_disk_guard:
        btst #0,native_disk_guard_enabled(pc)
        beq.s native_disk_guard_return
        btst #2,$bfe001.l
        bne.s native_disk_guard_return
        move.w #16384,$dff024.l
        move.w #2,$dff09c.l
        moveq #29,d0
        lea -36(a6),sp
        bra.w diskio_L00c0
native_disk_guard_return:
        rts
native_disk_guard_enabled: dc.b 0
        even
'''
out = root / 'scratchpad/trackloader/native_game/guarded_diskio.s'
out.parent.mkdir(parents=True, exist_ok=True)
out.write_text('; Generated by tools/trackloader/make_guarded_diskio.py\n' + source)
