#!/usr/bin/env python3
"""Build offline-aligned, integer overlap-add auditions; no runtime search needed."""
import hashlib
import json
import struct
from pathlib import Path
import numpy as np
from scipy import signal
from scipy.io import wavfile
from locate_ending_focus import ROOT, RATE, decode

OUT = ROOT/'scratchpad/audio/ending_focus_overlap'
BANK = ROOT/'scratchpad/audio/codec_audition_budget_250_preboost_pc_tracks/focus_expanded_fibonacci.wav'

def schedule(x, start, count, grain, search):
    hop = grain//2
    starts = [start]
    for k in range(1, (count+hop-1)//hop):
        nominal = start + k*hop//8
        lo = max(0, nominal-search)
        hi = min(len(x)-grain, nominal+search)
        q = x[starts[-1]+hop:starts[-1]+grain].astype(np.float64)
        block = x[lo:hi+hop].astype(np.float64)
        # Normalized dot product; search is performed only on the host.
        corr = signal.correlate(block, q, mode='valid', method='fft')
        energy = np.r_[0, np.cumsum(block*block)]
        norm = np.sqrt(np.maximum(energy[hop:]-energy[:-hop], 1)*max(float(q@q),1))
        scores = corr/norm
        starts.append(lo+int(np.argmax(scores)))
    return starts

def render(x, starts, grain, count):
    hop = grain//2
    # Complementary Q8 ramps. Target implementation needs only two reads,
    # two small integer products, an add and a shift per output sample.
    w = np.arange(hop, dtype=np.int32)*256//hop
    chunks = [x[starts[0]:starts[0]+hop].astype(np.int32)]
    for prev, cur in zip(starts, starts[1:]):
        a=x[prev+hop:prev+grain].astype(np.int32)
        b=x[cur:cur+hop].astype(np.int32)
        chunks.append((a*(256-w)+b*w+128)//256)
    y=np.concatenate(chunks)[:count]
    assert len(y)==count and y.min()>=-128 and y.max()<=127
    return y.astype(np.int8)

def main():
    OUT.mkdir(parents=True, exist_ok=True)
    alignment=json.loads((ROOT/'scratchpad/audio/ending_focus/report.json').read_text())['results'][0]
    assert alignment['asset']=='music4.dat' and alignment['best']['stretch']==8
    start=round(alignment['best']['source_start_seconds']*RATE)
    count=round(alignment['duration_seconds']*RATE)
    x=np.clip(np.rint(decode(BANK)*128),-128,127).astype(np.int8)
    results=[]; items=[]
    for grain in (256,512,1024,2048,4096):
        for search in (0,256):
            name=f'grain_{grain}_search_{search}'
            starts=schedule(x,start,count,grain,search)
            assert all(0<=s<=len(x)-grain for s in starts)
            y=render(x,starts,grain,count)
            wavfile.write(OUT/(name+'.wav'),RATE,y.astype(np.int16)*256)
            data=b''.join(struct.pack('>I',s) for s in starts)
            (OUT/(name+'.offsets')).write_bytes(data)
            if grain==512 and search==256:
                (ROOT/'assets/ending_focus_offsets.inc').write_text(
                    '/* Generated by tools/audio/audition_ending_overlap.py; 512/256 aligned. */\n'+
                    ''.join(','.join(str(v)+'u' for v in starts[i:i+12])+',\n' for i in range(0,len(starts),12)))
            # Independently read the exported schedule and reproduce identical output.
            restored=[v[0] for v in struct.iter_unpack('>I',data)]
            assert np.array_equal(y,render(x,restored,grain,count))
            results.append(dict(name=name,grain_samples=grain,hop_samples=grain//2,
                search_radius_samples=search,schedule_entries=len(starts),schedule_bytes=len(data),
                output_samples=len(y),output_sha256=hashlib.sha256(y.tobytes()).hexdigest(),
                source_first_sample=starts[0],source_last_grain_sample=starts[-1]))
            label='Offline waveform alignment' if search else 'Fixed positions (comparison)'
            items.append(f'<h2>{grain} samples ({grain/RATE*1000:.1f} ms): {label}</h2><p>Schedule: {len(data):,} bytes; 8-bit output.</p><audio controls preload="none" src="{name}.wav"></audio>')
    report=dict(status='Host audition only; target CPU and audible quality not validated',
        bank=str(BANK.relative_to(ROOT)),bank_sha256=hashlib.sha256(BANK.read_bytes()).hexdigest(),
        source_start_seconds=start/RATE,stretch=8,sample_rate=RATE,
        arithmetic='signed 8-bit samples, complementary Q8 linear ramps, (sum+128)//256',
        offset_format='headerless big-endian uint32 logical sample offsets; parameters in this JSON',
        variants=results)
    (OUT/'report.json').write_text(json.dumps(report,indent=2)+'\n')
    (OUT/'index.html').write_text('''<!doctype html><meta charset="utf-8"><title>68000 ending stretch auditions</title>
<style>body{font:18px system-ui;max-width:900px;margin:40px auto;padding:16px;background:#171923;color:#eee}audio{width:100%}</style>
<h1>Ending stretch: inexpensive synthesis candidates</h1>
<p>Focus at 24.35 seconds, stretched 8× using the reconstructed Amiga bank. These samples use integer overlap-add, with no runtime waveform search or FFT. The aligned variants search ±21.3 ms during the build. Larger grains may reduce rapid repetition but smear changes. Listen before selecting a variant; no quality winner is assumed.</p>
<p>All candidate files have the same duration. Original levels retained; the PC reference may be quieter. Beginning uses an unblended half-grain; the final block is trimmed. End fades/loop joins are not designed yet. This is a host prototype, not integrated or benchmarked on the Amiga.</p>
<h2>PC ending reference</h2><audio controls preload="none" src="../ending_focus/music4_reference.wav"></audio>
<h2>FFmpeg stretch of the same Amiga bank</h2><audio controls preload="none" src="../ending_focus/music4_bank_stretch.wav"></audio>'''+''.join(items))
    print(json.dumps(report,indent=2)); print(OUT/'index.html')

if __name__=='__main__': main()
