#!/usr/bin/env python3
"""Offline original PC clips -> word-aligned signed 8-bit Paula PCM."""
import hashlib,json,subprocess
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2]
NAMES=['begin','excellent','gameover','start','die','rankup','line','triangle','square','pentagon','hexagon','menuselect','menuchoose','awesome','wonderful','superhexagon']
def main():
    out=ROOT/'out';out.mkdir(exist_ok=True)
    bank=bytearray(); clips=[]; rows=[]
    for ident,name in enumerate(NAMES):
        source=ROOT/'assets/sounds'/f'{name}.ogg'
        pcm=subprocess.check_output(['ffmpeg','-v','error','-i',str(source),'-ac','1','-ar','8000','-f','s8','-'])
        # Preserve every audible sample and the onset; discard digital zero
        # tails only. menuselect belongs to PC screens not implemented here.
        original_bytes=len(pcm)
        pcm=pcm.rstrip(b'\0') if name!='menuselect' else b''
        pcm+=b'\0'*(len(pcm)&1)
        assert len(pcm)<=131070 and (len(pcm)>=2 or name=='menuselect')
        rows.append(f'    {{{len(bank)}, {len(pcm)//2}}}, /* {ident}: {name} */')
        clips.append({'id':ident,'name':name,'source_sha256':hashlib.sha256(source.read_bytes()).hexdigest(),'offset':len(bank),'bytes':len(pcm),'original_bytes':original_bytes,'omitted':name=='menuselect'})
        bank+=pcm
    (out/'sfx.pcm').write_bytes(bank)
    (out/'sfx_samples.h').write_text('/* Generated by prepare_sfx.py; offsets in bytes, lengths in words. */\nstatic const struct { unsigned offset; unsigned short words; } sfx_samples[16]={\n'+'\n'.join(rows)+'\n};\n')
    (ROOT/'soundtrack/sfx_assets.json').write_text(json.dumps({'sample_rate':8000,'format':'signed 8-bit mono, even padded','bytes':len(bank),'sha256':hashlib.sha256(bank).hexdigest(),'clips':clips},indent=2)+'\n')
    print(len(bank),'bytes,',sum(c['bytes']>0 for c in clips),'playable aligned clips')
if __name__=='__main__':main()
