#!/usr/bin/env python3
"""Compact original-machine-code cases for the host/68000 shared self-test."""
from pathlib import Path
import gzip
root=Path(__file__).resolve().parents[1]
rows=[]
with gzip.open(root/'tests/fixtures/pc_progression_native.txt.gz','rt') as f:
    for line in f:
        a=line.split();stage,hyper,scenario,seed,tick=map(int,a[:5])
        if seed or scenario==1: continue
        start=0 if not scenario else (7198 if hyper else 10798)+(7200 if scenario==3 else 0)
        if tick!=start+(3 if scenario else 1): continue
        assert int(a[17])==1
        # initial profile/scenario; expected chosen, speed, wave, draws,
        # record count/hash, rotation and shape counter.
        rows.append([stage,hyper,scenario]+[int(a[i]) for i in (18,8,10,16,19,20,15,21)])
out='/* Generated by tools/build_progression_checks.py; native fixture subset. */\n'
out+='\n'.join('    {'+','.join(str(v)+'u' for v in r)+'},' for r in rows)+'\n'
(root/'tests/progression_cases.inc').write_text(out)
