#!/usr/bin/env python3
"""Factor verified integer RNG paths into shared immutable emission/decision nodes.

Only the generated C tables ship. Fixtures and this tool stay on the host.
The graph preserves emitted record order and random-domain traversal, with no
runtime floating point, expanded-outcome lookup, or allocation.
"""
import collections,gzip,json,hashlib
from pathlib import Path
ROOT=Path(__file__).resolve().parent.parent
source=ROOT/'tests/fixtures/pc_wave_branches.jsonl.gz'
rows=[json.loads(l) for l in gzip.open(source,'rt')]
nodes={};records={};edges={}
def build(rows,depth=0):
 prefix=[]
 for i in range(min(len(r['walls']) for r in rows)):
  w=rows[0]['walls'][i]
  if any(r['walls'][i]!=w for r in rows):break
  assert w[3:]==[0,1]
  assert all(-32768<=v<=32767 for v in w[:3])
  prefix.append(tuple(w[:3]))
 rows=[dict(r,walls=r['walls'][len(prefix):]) for r in rows]
 prefix=tuple(prefix);records.setdefault(prefix,len(records))
 if len(rows[0]['rolls'])==depth:
  assert len(rows)==1 and not rows[0]['walls']
  r=rows[0];base=round(r['delay']*22/20)
  assert abs(base*20/22-r['delay'])<.001
  key=(prefix,(),(base,r['marker_wait'],r['spawn_base']))
 else:
  groups=collections.defaultdict(list)
  for r in rows:groups[r['rolls'][depth]].append(r)
  assert sorted(groups)==list(range(len(groups)))
  branches=[build(groups[k],depth+1) for k in sorted(groups)]
  compact=[]
  for k,n in enumerate(branches):
   if compact and compact[-1][1]==n:compact[-1]=(k+1,n)
   else:compact.append((k+1,n))
  key=(prefix,tuple(compact),None);edges.setdefault(tuple(compact),len(edges))
 nodes.setdefault(key,len(nodes));return nodes[key]
roots={w:build([r for r in rows if r['wave']==w]) for w in sorted({r['wave'] for r in rows})}
record_data=[];record_offsets={}
for p in records:record_offsets[p]=len(record_data);record_data.extend(p)
edge_data=[];edge_offsets={}
for e in edges:edge_offsets[e]=len(edge_data);edge_data.extend(e)
assert max(len(nodes),len(record_data),len(edge_data))<65536
out=['/* Generated by tools/build_wave_data.py; do not edit. */',
     '/* Input SHA256: '+hashlib.sha256(source.read_bytes()).hexdigest()+' */',
     'static const PcWaveRecord wave_records[] = {']
out += ['    {%d,%d,%d},'%r for r in record_data];out+=['};','static const PcWaveEdge wave_edges[] = {']
out += ['    {%d,%d},'%e for e in edge_data];out+=['};','static const PcWaveNode wave_nodes[] = {']
for p,e,end in nodes:
 base,wait,spawn=end if end else (0,0,0)
 out.append('    {%d,%d,%d,%d,%d,%d,%d,%d},'%(record_offsets[p],len(p),edge_offsets.get(e,0),len(e),e[-1][0] if e else 0,base,spawn,wait))
out+=['};','static const PcWaveRoot wave_roots[] = {']
out+=['    {%d,%d},'%(w,n) for w,n in roots.items()];out+=['};','']
(ROOT/'pc_wave_data.inc').write_text('\n'.join(out))
print(f'{len(roots)} waves, {len(nodes)} nodes, {len(record_data)} records, {len(edge_data)} edges; {len(nodes)*16+len(record_data)*6+len(edge_data)*4+len(roots)*4} table bytes')
