#!/usr/bin/env python3
"""Integer render arcs for the source's uninterrupted binary64 dt=1 morphs."""
from pathlib import Path
shrink=[0.0]
for _ in range(10):shrink.append(shrink[-1]+0.1)
grow=[1.0]
for _ in range(11):grow.append(max(0.0,grow[-1]-0.1))
grow.reverse()
out=['/* Generated by tools/build_morph_data.py. */','static const uint8_t arcs[2][4][12] = {']
for values in (shrink+[0.0],grow):
 out.append('    {')
 for sides in range(3,7):out.append('        {'+','.join(str(int(360/(sides-f))) for f in values)+'},')
 out.append('    },')
out+=['};','']
(Path(__file__).resolve().parent.parent/'pc_morph_data.inc').write_text('\n'.join(out))
