#!/usr/bin/env python3
"""Offline credit QR-L bitmaps; requires the Python qrcode package."""
from pathlib import Path
import qrcode
URLS=['https://www.distractionware.com','https://chipzelmusic.bandcamp.com',
      'https://www.infinitelives.net','https://flibitijibibo.com',
      'https://fontstruct.com/fontstructions/show/155156']
def main():
    sizes=[];offsets=[];packed=[]
    for url in URLS:
        qr=qrcode.QRCode(error_correction=qrcode.constants.ERROR_CORRECT_L,border=0)
        qr.add_data(url);qr.make(fit=True);matrix=qr.get_matrix();n=len(matrix)
        assert (n+8)*2<=86  # Four-module total quiet zone, 2px/module.
        sizes.append(n);offsets.append(len(packed))
        for row in matrix:
            for x in range(0,n,8):
                packed.append(sum(int(v)<<(7-i) for i,v in enumerate(row[x:x+8])))
    out='/* Generated by tools/build_credit_qr.py. MSB-first black modules. */\n'
    out+=''.join('/* '+u+' */\n' for u in URLS)
    for ty,name,data in [('unsigned char','size',sizes),('unsigned short','offset',offsets),('unsigned char','bits',packed)]:
        out+='static const '+ty+' credit_qr_'+name+'[]={'+','.join(map(str,data))+'};\n'
    (Path(__file__).resolve().parents[1]/'credit_qr.h').write_text(out)
    print(sizes,len(packed),'packed bytes')
if __name__=='__main__':main()
