import Foundation
import CoreGraphics
import CoreText
let args=CommandLine.arguments
let provider=CGDataProvider(url: URL(fileURLWithPath: args[1]) as CFURL)!
let cgfont=CGFont(provider)!
let probe=CTFontCreateWithGraphicsFont(cgfont,16,nil,nil)
var glyphs=[CGGlyph](repeating:0,count:26)
var chars=(65...90).map{UniChar($0)}
CTFontGetGlyphsForCharacters(probe,&chars,&glyphs,26)
var bounds=CGRect.null
for g in glyphs { var glyph=g; bounds=bounds.union(CTFontGetBoundingRectsForGlyphs(probe,.horizontal,&glyph,nil,1)) }
let size=16*min(14/bounds.width,14/bounds.height)
let font=CTFontCreateWithGraphicsFont(cgfont,size,nil,nil)
let baseline=1-bounds.minY*size/16
var output="/* Bump IT UP by Aaron Amar; CC BY-SA 3.0. Rasterised to 16x16.\n * See assets/fonts/BUMP_IT_UP_LICENSE.txt. Generated by build_menu_font.swift. */\nstatic const unsigned short menu_font16[26][16]={\n"
for g in glyphs {
 var data=[UInt8](repeating:0,count:256)
 data.withUnsafeMutableBytes { raw in
  let context=CGContext(data:raw.baseAddress,width:16,height:16,bitsPerComponent:8,bytesPerRow:16,space:CGColorSpaceCreateDeviceGray(),bitmapInfo:CGImageAlphaInfo.none.rawValue)!
  context.setShouldAntialias(false);context.setFillColor(gray:1,alpha:1)
  var glyph=g
  let box=CTFontGetBoundingRectsForGlyphs(font,.horizontal,&glyph,nil,1)
  var point=CGPoint(x:floor((16-box.width)/2-box.minX),y:baseline)
  CTFontDrawGlyphs(font,&glyph,&point,1,context)
 }
 var rows=[String]()
 for y in 0..<16 {var bits=0;for x in 0..<16 {if data[y*16+x]>127 {bits |= 1<<(15-x)}};rows.append(String(format:"0x%04x",bits))}
 output+=" {"+rows.joined(separator:",")+"},\n"
}
output+="};\n"
try output.write(toFile:args[2],atomically:true,encoding:.utf8)
