#!/usr/bin/env python3
"""Invalidate target objects when switching the optional steering assist."""
import sys
from pathlib import Path

mode, name = sys.argv[1:]
if mode not in ('0', '1'):
    raise SystemExit('CHEAT_MODE must be 0 or 1')
path = Path(name)
text = f'/* Generated by make. */\n#undef CHEAT_MODE\n#define CHEAT_MODE {mode}\n'
if not path.exists() or path.read_text() != text:
    path.write_text(text)
